###############################################################################
# Copyright (c) 2022-23, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
###############################################################################

###############################################################################
# VARIABLES
###############################################################################

variables:
# Tells Gitlab to recursively update the submodules when cloning the project.
  GIT_SUBMODULE_STRATEGY: recursive
# SHARED_CI CONFIGURATION
# Required information about GitHub repository
  GITHUB_PROJECT_NAME: "Quandary"
  GITHUB_PROJECT_ORG: "LLNL"
# Set the build-and-test command.
# Nested variables are allowed and useful to customize the job command. We
# prevent variable expansion so that you can define them at job level.
  JOB_CMD:
    value: ".ci-scripts/build_and_test.sh"
    expand: false

###############################################################################
# MAIN PIPELINE STAGES
###############################################################################

stages:
  - prerequisites
  - build-and-test
  - performance-measurements

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - when: never

###############################################################################
# INCLUDES
###############################################################################

include:
  # Sets ID tokens for every job using `default:`
  - project: 'lc-templates/id_tokens'
    file: 'id_tokens.yml'

  # Base pipeline templates and utilities
  - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/base-pipeline@v2026.02.1
    inputs:
      github_project_name: $GITHUB_PROJECT_NAME
      github_project_org: $GITHUB_PROJECT_ORG
      github_token: $GITHUB_TOKEN

  # Local custom variables (used for component inputs and forwarded to child pipelines)
  - local: '.gitlab/custom-variables.yml'

###############################################################################
# MACHINE PIPELINES
###############################################################################

# One job to generate the job list for all the subpipelines
generate-job-lists:
  stage: prerequisites
  tags: [shell, oslic]
  variables:
    RADIUSS_JOBS_PATH: ".ci-scripts/radiuss-spack-configs/gitlab/radiuss-jobs"
    LOCAL_JOBS_PATH: ".gitlab/jobs"
  script:
    - cat ${RADIUSS_JOBS_PATH}/dane.yml ${LOCAL_JOBS_PATH}/dane.yml > dane-jobs.yml
    - cat ${RADIUSS_JOBS_PATH}/tuolumne.yml ${LOCAL_JOBS_PATH}/tuolumne.yml > tuolumne-jobs.yml
  artifacts:
    paths:
      - dane-jobs.yml
      - tuolumne-jobs.yml

# DANE
dane-up-check:
  extends: [.dane, .machine-check]
  variables:
    ASSOCIATED_CHILD_PIPELINE: "dane-build-and-test"

dane-build-and-test:
  stage: build-and-test
  extends: [.dane]
  needs: [dane-up-check, generate-job-lists]
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/dane-pipeline@v2026.02.1
        inputs:
          job_cmd: $JOB_CMD
          shared_alloc: $DANE_SHARED_ALLOC
          job_alloc: $DANE_JOB_ALLOC
          github_project_name: $GITHUB_PROJECT_NAME
          github_project_org: $GITHUB_PROJECT_ORG
      - artifact: 'dane-jobs.yml'
        job: 'generate-job-lists'
    strategy: depend
    forward:
      pipeline_variables: true

# TUOLUMNE
tuolumne-up-check:
  extends: [.tuolumne, .machine-check]
  variables:
    ASSOCIATED_CHILD_PIPELINE: "tuolumne-build-and-test"

tuolumne-build-and-test:
  stage: build-and-test
  extends: [.tuolumne]
  needs: [tuolumne-up-check, generate-job-lists]
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/tuolumne-pipeline@v2026.02.1
        inputs:
          job_cmd: $JOB_CMD
          shared_alloc: $TUOLUMNE_SHARED_ALLOC
          job_alloc: $TUOLUMNE_JOB_ALLOC
          github_project_name: $GITHUB_PROJECT_NAME
          github_project_org: $GITHUB_PROJECT_ORG
      - artifact: 'tuolumne-jobs.yml'
        job: 'generate-job-lists'
    strategy: depend
    forward:
      pipeline_variables: true

# PERFORMANCE
performance-test:
  stage: performance-measurements
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/performance-pipeline@v2026.02.2
        inputs:
          job_cmd: $JOB_CMD
          perf_processing_cmd: "${CI_PROJECT_DIR}/tests/performance/convert_benchmark_format.py"
          perf_artifact_dir: $PERF_ARTIFACT_DIR
          perf_results_file: $PERF_RESULTS_FILE
          perf_processed_file: "processed_results.json"
          github_token: $GITHUB_WORKFLOW_TOKEN
          github_project_name: $GITHUB_PROJECT_NAME
          github_project_org: $GITHUB_PROJECT_ORG
          dane_perf_alloc: $DANE_PERF_ALLOC
      - local: '.gitlab/jobs/performances.yml'
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    CI_MACHINE: "performance"
    PERFORMANCE_TESTS: "true"
    PERF_ARTIFACT_DIR: "performance-results"
    PERF_RESULTS_FILE: "benchmark_results.json"
