site_name: Quandary
site_description: Documentation for Quandary
site_author: LLNL
site_url: https://software.llnl.gov/quandary/

plugins:
  - search
  - macros:
      j2_variable_start_string: '[['
      j2_variable_end_string: ']]'
      j2_comment_start_string: '[#'
      j2_comment_end_string: '#]'
  - bibtex:
      bib_file: "doc/user_guide.bib"
      enable_inline_citations: false

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.snippets:
      base_path: ['.', 'docs']
      check_paths: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: mkdocs

nav:
  - Home: index.md
  - User Guide: user-guide.md

use_directory_urls: true
docs_dir: docs/mkdocs
site_dir: site
