#!/bin/tcsh

#SBATCH -t 00:10:00
#SBATCH -p pbatch
#SBATCH -o out.%j
#SBATCH -e err.%j
#SBATCH -J AxC
#SBATCH --ntasks=36

echo -n 'This machine is '; hostname
echo -n 'My jobid is '; echo $SLURM_JOBID
echo -n 'Timestamp START: ';date 

srun -n36 ./quandary AxC.cfg 

echo -n 'Timestamp ';date
echo 'Done'
echo -n 'Timestamp END: ';date

