name: Deploy Doxygen Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Doxygen Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen Documentation
      run: |
        mkdir build
        cd build
        cmake -DENABLE_MPI=OFF -DBUILD_QUANDARY=OFF ..
        cmake --build . --target quandary_doxygen

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/doxygen/html
        destination_dir: doxygen
